apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: extenddevices.nodesystem.k8s.io
spec:
  group: device.k8s.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: extenddevices
    singular: extenddevice
    kind: ExtendDevice
    shortNames:
      - ed
  validation:
    openAPIV3Schema:
      type: object
      required:
        - spec
      properties:
        spec:
          type: object
