---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: device-manager-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: device-manager-role
rules:
  - apiGroups:
      - device.k8s.io
    resources:
      - extenddevices
    verbs:
      - "*"
  - apiGroups:
      - device.k8s.io
    resources:
      - extenddevices/status
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: device-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: device-manager-role
subjects:
  - kind: ServiceAccount
    name: device-manager-sa
    namespace: {{ .Release.Namespace }}
