/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	v1alpha1 "hikvision.com/cloud/device-manager/pkg/crd/apis/device.k8s.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeExtendDevices implements ExtendDeviceInterface
type FakeExtendDevices struct {
	Fake *FakeDeviceV1alpha1
}

var ExtendDevicesResource = schema.GroupVersionResource{Group: "device.k8s.io", Version: "v1alpha1", Resource: "extenddevices"}

var ExtendDevicesKind = schema.GroupVersionKind{Group: "device.k8s.io", Version: "v1alpha1", Kind: "ExtendDevice"}

// Get takes name of the ExtendDevice, and returns the corresponding ExtendDevice object, and an error if there is any.
func (c *FakeExtendDevices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ExtendDevice, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(ExtendDevicesResource, name), &v1alpha1.ExtendDevice{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendDevice), err
}

// List takes label and field selectors, and returns the list of ExtendDevices that match those selectors.
func (c *FakeExtendDevices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ExtendDeviceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(ExtendDevicesResource, ExtendDevicesKind, opts), &v1alpha1.ExtendDeviceList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ExtendDeviceList{ListMeta: obj.(*v1alpha1.ExtendDeviceList).ListMeta}
	for _, item := range obj.(*v1alpha1.ExtendDeviceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ExtendDevices.
func (c *FakeExtendDevices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(ExtendDevicesResource, opts))
}

// Create takes the representation of a ExtendDevice and creates it.  Returns the server's representation of the ExtendDevice, and an error, if there is any.
func (c *FakeExtendDevices) Create(ctx context.Context, ExtendDevice *v1alpha1.ExtendDevice) (result *v1alpha1.ExtendDevice, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(ExtendDevicesResource, ExtendDevice), &v1alpha1.ExtendDevice{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendDevice), err
}

// Update takes the representation of a ExtendDevice and updates it. Returns the server's representation of the ExtendDevice, and an error, if there is any.
func (c *FakeExtendDevices) Update(ctx context.Context, ExtendDevice *v1alpha1.ExtendDevice) (result *v1alpha1.ExtendDevice, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(ExtendDevicesResource, ExtendDevice), &v1alpha1.ExtendDevice{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendDevice), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeExtendDevices) UpdateStatus(ctx context.Context, ExtendDevice *v1alpha1.ExtendDevice) (*v1alpha1.ExtendDevice, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(ExtendDevicesResource, "status", ExtendDevice), &v1alpha1.ExtendDevice{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendDevice), err
}

// Delete takes name of the ExtendDevice and deletes it. Returns an error if one occurs.
func (c *FakeExtendDevices) Delete(ctx context.Context, name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(ExtendDevicesResource, name), &v1alpha1.ExtendDevice{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeExtendDevices) DeleteCollection(ctx context.Context, options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(ExtendDevicesResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ExtendDeviceList{})
	return err
}

// Patch applies the patch and returns the patched ExtendDevice.
func (c *FakeExtendDevices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ExtendDevice, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(ExtendDevicesResource, name, pt, data, subresources...), &v1alpha1.ExtendDevice{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExtendDevice), err
}
